# PRESENT CARD DEFINITIONS
# CHECK INPUT AGAINST TERM
# PASS COMMANDS TO MODEL
# DECKS AND CARDS  AND INPUT FROM USER
module GameController
# LOAD TEXT FILE 
# PARSE TEXT FILE
# ASK DECK TO MAKE NEW DECK
# 
end
